### ISSUE TITLE
求助，磁盘有问题？？？

### ISSUE THREAD

**Issue by 11235yuan** [yichen115/w4sp-lab#1]
我使用VirtualBox 安装虚拟机，用您提供的磁盘做存储空间，勾选之后会报错，无法打开磁盘？？？
用VMware 也尝试了，也不行！！！
您能提供一个  .ova 格式的镜像吗？

另外我自己部署的时候,在kali 2016.2 上 运行命令 sudo python w4sp_webapp.py 会报    os.getlogin()的错误， OSError:[Error 2] No such file or directory。您遇到过这种情况吗？

**Comment by yichen115** [comment]
> 

我的虚拟机也删掉了🤦‍♂️我重新搭一个试试，要是能运行的话打包一个给你😀

**Comment by yichen115** [comment]
链接: https://pan.baidu.com/s/12GfuEg0_sqDiAwyvw9_aKA 提取码: 9629 这是ova格式的
